### model
model_name_or_path: meta-llama/Meta-Llama-3.1-8B-Instruct
### method
stage: sft
do_train: true
finetuning_type: lora
lora_target: all

### dataset
dataset: arc_wending_data, arc_gen_v010
template: llama3
cutoff_len: 10000
max_samples: 40000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: /home/kh844/Fine-tune/LLaMA-Factory/sub/saves/Meta-Llama-3.1-8B-Instruct-both/
logging_steps: 100
save_steps: 100
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 1.0e-4
num_train_epochs: 5.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 1800000000

### eval
val_size: 0.1
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 300
